---
version: '3'

services:

  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: loretta
      WORDPRESS_DB_PASSWORD: shuga
      WORDPRESS_DB_NAME: wpdb

    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: wpdb
      MYSQL_USER: loretta
      MYSQL_PASSWORD: shuga
      MYSQL_ROOT_PASSWORD: '1'

    volumes:
    
      - db:/var/lib/mysql
    networks:
      - default

volumes:
  wordpress:
  db: